USE [master]
GO

/****** Object:  Database [Database Chernovik]    Script Date: 24.02.2022 11:39:06 ******/
CREATE DATABASE [Database Chernovik]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Database', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Database.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Database_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Database_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Database Chernovik].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Database Chernovik] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Database Chernovik] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Database Chernovik] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Database Chernovik] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Database Chernovik] SET ARITHABORT OFF 
GO

ALTER DATABASE [Database Chernovik] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Database Chernovik] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Database Chernovik] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Database Chernovik] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Database Chernovik] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Database Chernovik] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Database Chernovik] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Database Chernovik] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Database Chernovik] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Database Chernovik] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Database Chernovik] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Database Chernovik] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Database Chernovik] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Database Chernovik] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Database Chernovik] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Database Chernovik] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Database Chernovik] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Database Chernovik] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Database Chernovik] SET  MULTI_USER 
GO

ALTER DATABASE [Database Chernovik] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Database Chernovik] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Database Chernovik] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Database Chernovik] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Database Chernovik] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Database Chernovik] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Database Chernovik] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Database Chernovik] SET  READ_WRITE 
GO

